"""
Applies Spanish label translations to all catalog JSON files in
assets/catalogs/_derived/.

Run from the trama_campus_frontend directory:
    python3 tool/translate_catalogs.py
"""

import json
import os

CATALOGS_DIR = os.path.join("assets", "catalogs", "_derived")

# ---------------------------------------------------------------------------
# Translation dictionaries
# ---------------------------------------------------------------------------

SKILL_SETS = {
    "engineering": "Ingeniería",
    "software_and_technology": "Software y Tecnología",
    "data_and_analytics": "Datos y Analítica",
    "health_and_medicine": "Salud y Medicina",
    "business_and_management": "Negocios y Gestión",
    "finance_and_accounting": "Finanzas y Contabilidad",
    "law_and_compliance": "Derecho y Cumplimiento",
    "communication_and_media": "Comunicación y Medios",
    "design_and_creative": "Diseño y Creatividad",
    "architecture_and_urbanism": "Arquitectura y Urbanismo",
    "education_and_pedagogy": "Educación y Pedagogía",
    "humanities_and_research": "Humanidades e Investigación",
    "sports_and_physical": "Deportes y Actividad Física",
    "arts_and_performance": "Artes y Espectáculo",
}

SKILL_ITEMS = {
    "cad design": "Diseño CAD",
    "mechanical design": "Diseño Mecánico",
    "manufacturing processes": "Procesos de Manufactura",
    "thermodynamics": "Termodinámica",
    "fluid mechanics": "Mecánica de Fluidos",
    "structural analysis": "Análisis Estructural",
    "reinforced concrete design": "Diseño en Concreto Armado",
    "hydraulics": "Hidráulica",
    "surveying & topography": "Topografía y Geodesia",
    "geotechnical engineering": "Ingeniería Geotécnica",
    "construction management": "Gestión de Construcción",
    "electrical circuits": "Circuitos Eléctricos",
    "power systems": "Sistemas de Potencia",
    "embedded systems": "Sistemas Embebidos",
    "robotics": "Robótica",
    "industrial automation": "Automatización Industrial",
    "control systems": "Sistemas de Control",
    "plc programming": "Programación PLC",
    "operations research": "Investigación de Operaciones",
    "lean manufacturing": "Manufactura Esbelta",
    "six sigma": "Six Sigma",
    "supply chain management": "Gestión de Cadena de Suministro",
    "quality management": "Gestión de Calidad",
    "project management (engineering)": "Gestión de Proyectos (Ingeniería)",
    "materials science": "Ciencia de Materiales",
    "renewable energy": "Energía Renovable",
    "sustainability engineering": "Ingeniería Sustentable",
    "mechatronics integration": "Integración Mecatrónica",
    "programming fundamentals": "Fundamentos de Programación",
    "web development": "Desarrollo Web",
    "mobile development": "Desarrollo Móvil",
    "database management": "Gestión de Bases de Datos",
    "cloud computing": "Cómputo en la Nube",
    "devops": "DevOps",
    "cybersecurity": "Ciberseguridad",
    "networking": "Redes",
    "software architecture": "Arquitectura de Software",
    "version control": "Control de Versiones",
    "agile methodologies": "Metodologías Ágiles",
    "digital business": "Negocios Digitales",
    "statistical analysis": "Análisis Estadístico",
    "probability theory": "Teoría de Probabilidad",
    "data visualization": "Visualización de Datos",
    "machine learning": "Machine Learning",
    "deep learning": "Deep Learning",
    "natural language processing": "Procesamiento de Lenguaje Natural",
    "econometrics": "Econometría",
    "predictive modeling": "Modelado Predictivo",
    "survey research": "Investigación por Encuesta",
    "data engineering": "Ingeniería de Datos",
    "anatomy": "Anatomía",
    "physiology": "Fisiología",
    "pathology": "Patología",
    "pharmacology": "Farmacología",
    "clinical diagnosis": "Diagnóstico Clínico",
    "patient care": "Atención al Paciente",
    "surgery": "Cirugía",
    "medical imaging": "Imagen Médica",
    "public health": "Salud Pública",
    "epidemiology": "Epidemiología",
    "nutrition science": "Ciencias de la Nutrición",
    "dietetics": "Dietética",
    "clinical psychology": "Psicología Clínica",
    "cognitive behavioral therapy": "Terapia Cognitivo-Conductual",
    "bioethics": "Bioética",
    "leadership": "Liderazgo",
    "strategic planning": "Planeación Estratégica",
    "project management": "Gestión de Proyectos",
    "operations management": "Gestión de Operaciones",
    "marketing strategy": "Estrategia de Marketing",
    "brand management": "Gestión de Marca",
    "sales": "Ventas",
    "negotiation": "Negociación",
    "human resources management": "Gestión de Recursos Humanos",
    "talent acquisition": "Adquisición de Talento",
    "organizational behavior": "Comportamiento Organizacional",
    "entrepreneurship": "Emprendimiento",
    "customer experience": "Experiencia del Cliente",
    "tourism management": "Gestión Turística",
    "gastronomy": "Gastronomía",
    "corporate social responsibility": "Responsabilidad Social Empresarial",
    "financial accounting": "Contabilidad Financiera",
    "managerial accounting": "Contabilidad Gerencial",
    "auditing": "Auditoría",
    "financial modeling": "Modelado Financiero",
    "corporate finance": "Finanzas Corporativas",
    "investment analysis": "Análisis de Inversiones",
    "portfolio management": "Gestión de Portafolio",
    "risk management": "Gestión de Riesgo",
    "actuarial science": "Ciencias Actuariales",
    "tax planning": "Planeación Fiscal",
    "banking operations": "Operaciones Bancarias",
    "civil law": "Derecho Civil",
    "criminal law": "Derecho Penal",
    "constitutional law": "Derecho Constitucional",
    "corporate law": "Derecho Corporativo",
    "tax law": "Derecho Fiscal",
    "international law": "Derecho Internacional",
    "legal writing": "Redacción Jurídica",
    "mediation & arbitration": "Mediación y Arbitraje",
    "public administration": "Administración Pública",
    "human rights": "Derechos Humanos",
    "international relations": "Relaciones Internacionales",
    "geopolitics": "Geopolítica",
    "diplomacy": "Diplomacia",
    "international security": "Seguridad Internacional",
    "journalism": "Periodismo",
    "editorial writing": "Redacción Editorial",
    "public relations": "Relaciones Públicas",
    "crisis communication": "Comunicación en Crisis",
    "social media management": "Gestión de Redes Sociales",
    "content creation": "Creación de Contenido",
    "videography": "Videografía",
    "sound design": "Diseño de Sonido",
    "podcasting": "Podcasting",
    "storytelling": "Narrativa",
    "broadcasting": "Radiodifusión",
    "graphic design": "Diseño Gráfico",
    "typography": "Tipografía",
    "illustration": "Ilustración",
    "branding": "Branding",
    "ux research": "Investigación UX",
    "ui design": "Diseño UI",
    "product design": "Diseño de Producto",
    "industrial design": "Diseño Industrial",
    "fashion design": "Diseño de Moda",
    "pattern making": "Patronaje",
    "textile innovation": "Innovación Textil",
    "3d modeling": "Modelado 3D",
    "motion graphics": "Motion Graphics",
    "animation": "Animación",
    "architectural drafting": "Dibujo Arquitectónico",
    "bim modeling": "Modelado BIM",
    "interior design": "Diseño de Interiores",
    "urban planning": "Planeación Urbana",
    "landscape architecture": "Arquitectura de Paisaje",
    "sustainable architecture": "Arquitectura Sustentable",
    "heritage conservation": "Conservación del Patrimonio",
    "architectural rendering": "Renderizado Arquitectónico",
    "curriculum design": "Diseño Curricular",
    "pedagogical planning": "Planeación Pedagógica",
    "educational assessment": "Evaluación Educativa",
    "adult learning": "Andragogía",
    "educational leadership": "Liderazgo Educativo",
    "instructional design": "Diseño Instruccional",
    "psychopedagogy": "Psicopedagogía",
    "philosophy": "Filosofía",
    "ethics": "Ética",
    "logic": "Lógica",
    "history": "Historia",
    "anthropology": "Antropología",
    "cultural studies": "Estudios Culturales",
    "theology": "Teología",
    "hermeneutics": "Hermenéutica",
    "creative writing": "Escritura Creativa",
    "academic writing": "Escritura Académica",
    "translation": "Traducción",
    "foreign languages": "Idiomas Extranjeros",
    "linguistics": "Lingüística",
    "classical studies": "Estudios Clásicos",
    "athletic training": "Entrenamiento Atlético",
    "strength & conditioning": "Fuerza y Acondicionamiento",
    "team sports": "Deportes de Equipo",
    "martial arts": "Artes Marciales",
    "boxing": "Boxeo",
    "brazilian jiu-jitsu": "Jiu-Jitsu Brasileño",
    "yoga": "Yoga",
    "sports coaching": "Entrenamiento Deportivo",
    "sports nutrition": "Nutrición Deportiva",
    "sports psychology": "Psicología del Deporte",
    "outdoor adventure": "Aventura al Aire Libre",
    "climbing": "Escalada",
    "swimming": "Natación",
    "music theory": "Teoría Musical",
    "musical performance": "Interpretación Musical",
    "composition": "Composición",
    "singing": "Canto",
    "dance": "Danza",
    "acting": "Actuación",
    "theater direction": "Dirección Teatral",
    "painting": "Pintura",
    "sculpture": "Escultura",
    "photography": "Fotografía",
    "cinematography": "Cinematografía",
    "film direction": "Dirección de Cine",
    "default": "General",
    "sports performance analysis": "Análisis de Rendimiento Deportivo",
    "coaching": "Coaching",
    "event management": "Gestión de Eventos",
    "sports administration": "Administración del Deporte",
}

HOBBY_SETS = {
    "sports_and_fitness": "Deportes y Fitness",
    "combat_and_martial_arts": "Artes Marciales y Combate",
    "outdoor_and_adventure": "Aire Libre y Aventura",
    "arts_and_crafts": "Artes y Manualidades",
    "music_and_performance": "Música y Espectáculo",
    "gaming": "Gaming",
    "reading_and_writing": "Lectura y Escritura",
    "tech_and_making": "Tecnología y Creación",
    "cooking_and_gastronomy": "Cocina y Gastronomía",
    "photography_and_film": "Fotografía y Cine",
    "travel_and_culture": "Viajes y Cultura",
    "community_and_service": "Comunidad y Servicio",
}

HOBBY_ITEMS = {
    "running": "Correr",
    "cycling": "Ciclismo",
    "swimming": "Natación",
    "triathlon": "Triatlón",
    "weightlifting": "Levantamiento de Pesas",
    "crossfit": "CrossFit",
    "calisthenics": "Calistenia",
    "yoga": "Yoga",
    "soccer": "Fútbol",
    "basketball": "Basquetbol",
    "volleyball": "Voleibol",
    "american football": "Fútbol Americano",
    "tennis": "Tenis",
    "padel": "Pádel",
    "badminton": "Bádminton",
    "surfing": "Surf",
    "sailing": "Vela",
    "kayaking": "Kayak",
    "diving": "Buceo",
    "boxing": "Boxeo",
    "muay thai": "Muay Thai",
    "karate": "Kárate",
    "taekwondo": "Taekwondo",
    "brazilian jiu-jitsu": "Jiu-Jitsu Brasileño",
    "judo": "Judo",
    "wrestling": "Lucha",
    "mma": "MMA",
    "krav maga": "Krav Maga",
    "hiking": "Senderismo",
    "trekking": "Trekking",
    "backpacking": "Mochilero",
    "camping": "Camping",
    "rock climbing": "Escalada en Roca",
    "bouldering": "Bouldering",
    "mountaineering": "Montañismo",
    "skiing": "Esquí",
    "snowboarding": "Snowboard",
    "mountain biking": "Mountain Bike",
    "skateboarding": "Skate",
    "fishing": "Pesca",
    "drawing": "Dibujo",
    "painting": "Pintura",
    "calligraphy": "Caligrafía",
    "digital art": "Arte Digital",
    "knitting": "Tejido con Agujas",
    "sewing": "Costura",
    "embroidery": "Bordado",
    "crochet": "Crochet",
    "pottery": "Alfarería",
    "sculpting": "Escultura",
    "origami": "Origami",
    "woodworking": "Carpintería",
    "jewelry making": "Joyería",
    "leather crafting": "Marroquinería",
    "guitar": "Guitarra",
    "piano": "Piano",
    "drums": "Batería",
    "violin": "Violín",
    "bass": "Bajo",
    "djing": "DJing",
    "choir singing": "Canto Coral",
    "solo singing": "Canto Solo",
    "salsa": "Salsa",
    "hip hop dance": "Baile Hip Hop",
    "ballet": "Ballet",
    "contemporary dance": "Danza Contemporánea",
    "acting": "Actuación",
    "improv": "Improvisación",
    "stand-up comedy": "Stand-up Comedy",
    "rpg games": "Juegos de Rol",
    "fps games": "Juegos FPS",
    "strategy games": "Juegos de Estrategia",
    "indie games": "Juegos Indie",
    "chess": "Ajedrez",
    "go": "Go",
    "tabletop rpg": "RPG de Mesa",
    "strategy board games": "Juegos de Mesa de Estrategia",
    "card games": "Juegos de Cartas",
    "competitive esports": "Esports Competitivo",
    "sudoku": "Sudoku",
    "crosswords": "Crucigramas",
    "rubik's cube": "Cubo de Rubik",
    "escape rooms": "Escape Rooms",
    "reading novels": "Leer Novelas",
    "reading poetry": "Leer Poesía",
    "sci-fi & fantasy reading": "Ciencia Ficción y Fantasía",
    "reading non-fiction": "Leer No Ficción",
    "reading philosophy": "Leer Filosofía",
    "reading biography": "Leer Biografías",
    "history reading": "Historia",
    "creative writing": "Escritura Creativa",
    "journaling": "Journaling",
    "blogging": "Blogging",
    "poetry writing": "Escritura de Poesía",
    "reading comics": "Leer Cómics",
    "reading manga": "Leer Manga",
    "drawing comics": "Dibujar Cómics",
    "coding for fun": "Programar por Pasión",
    "open source contribution": "Contribución Open Source",
    "hackathons": "Hackathons",
    "competitive programming": "Programación Competitiva",
    "robotics hobby": "Robótica",
    "arduino projects": "Proyectos Arduino",
    "3d printing": "Impresión 3D",
    "drone flying": "Vuelo con Drones",
    "indie game dev": "Desarrollo de Videojuegos Indie",
    "pixel art": "Pixel Art",
    "game modding": "Modding de Juegos",
    "pc building": "Ensamble de PC",
    "cooking": "Cocinar",
    "meal prepping": "Meal Prep",
    "grilling & bbq": "Asado y BBQ",
    "baking": "Horneado",
    "pastry making": "Repostería",
    "bread making": "Panificación",
    "cocktail mixing": "Coctelería",
    "coffee brewing": "Barismo",
    "tea culture": "Cultura del Té",
    "wine appreciation": "Enología",
    "craft beer": "Cerveza Artesanal",
    "food tourism": "Turismo Gastronómico",
    "portrait photography": "Fotografía de Retrato",
    "landscape photography": "Fotografía de Paisaje",
    "street photography": "Fotografía Callejera",
    "astrophotography": "Astrofotografía",
    "watching films": "Ver Películas",
    "film analysis": "Análisis de Cine",
    "watching anime": "Ver Anime",
    "documentary watching": "Ver Documentales",
    "video editing": "Edición de Video",
    "vlogging": "Vlogging",
    "solo travel": "Viaje Solo",
    "road trips": "Viajes por Carretera",
    "language learning": "Aprender Idiomas",
    "cultural exchange": "Intercambio Cultural",
    "concerts": "Conciertos",
    "festivals": "Festivales",
    "theater going": "Ir al Teatro",
    "sports events": "Eventos Deportivos",
    "museum visiting": "Visitar Museos",
    "historical tourism": "Turismo Histórico",
    "architecture visiting": "Turismo Arquitectónico",
    "volunteering": "Voluntariado",
    "animal rescue": "Rescate Animal",
    "environmental activism": "Activismo Ambiental",
    "social activism": "Activismo Social",
    "tutoring": "Tutoría",
    "religious community": "Comunidad Religiosa",
    "mentoring": "Mentoría",
    "birdwatching": "Observación de Aves",
    "default": "General",
    "photography": "Fotografía",
    "traveling": "Viajar",
    "video games": "Videojuegos",
}

SPORT_SETS = {
    "team_sports": "Deportes de Equipo",
    "racquet_sports": "Deportes de Raqueta",
    "combat_sports": "Deportes de Combate",
    "strength_training": "Entrenamiento de Fuerza",
    "endurance_sports": "Deportes de Resistencia",
    "outdoor_and_nature": "Aire Libre y Naturaleza",
    "mind_body": "Mente y Cuerpo",
    "aesthetic_sports": "Deportes Estéticos",
}

SPORT_ITEMS = {
    "soccer": "Fútbol",
    "american football": "Fútbol Americano",
    "rugby": "Rugby",
    "field hockey": "Hockey sobre Hierba",
    "basketball": "Basquetbol",
    "volleyball": "Voleibol",
    "handball": "Balonmano",
    "baseball": "Béisbol",
    "tennis": "Tenis",
    "padel": "Pádel",
    "badminton": "Bádminton",
    "table tennis": "Tenis de Mesa",
    "squash": "Squash",
    "boxing": "Boxeo",
    "muay thai": "Muay Thai",
    "karate": "Kárate",
    "taekwondo": "Taekwondo",
    "kickboxing": "Kickboxing",
    "brazilian jiu-jitsu": "Jiu-Jitsu Brasileño",
    "judo": "Judo",
    "wrestling": "Lucha",
    "mma": "MMA",
    "powerlifting": "Powerlifting",
    "weightlifting": "Levantamiento de Pesas",
    "bodybuilding": "Fisicoculturismo",
    "gym training": "Entrenamiento en Gimnasio",
    "crossfit": "CrossFit",
    "calisthenics": "Calistenia",
    "running": "Correr",
    "marathon": "Maratón",
    "trail running": "Trail Running",
    "cycling": "Ciclismo",
    "mountain biking": "Mountain Bike",
    "spinning": "Spinning",
    "swimming": "Natación",
    "triathlon": "Triatlón",
    "athletics": "Atletismo",
    "caminata": "Caminata",
    "hiking": "Senderismo",
    "trekking": "Trekking",
    "rock climbing": "Escalada en Roca",
    "bouldering": "Bouldering",
    "skiing": "Esquí",
    "snowboarding": "Snowboard",
    "surfing": "Surf",
    "sailing": "Vela",
    "kayaking": "Kayak",
    "skateboarding": "Skate",
    "yoga": "Yoga",
    "pilates": "Pilates",
    "dance": "Danza",
    "salsa": "Salsa",
    "ballet": "Ballet",
    "hip hop dance": "Baile Hip Hop",
    "gymnastics": "Gimnasia",
    "cheerleading": "Porrismo",
    "default": "General",
}

MUSIC_SETS = {
    "urban": "Urbana",
    "electronic": "Electrónica",
    "pop": "Pop",
    "rock": "Rock",
    "acoustic": "Acústica",
    "latin": "Latina",
    "classical": "Clásica",
    "jazz": "Jazz",
}

MUSIC_ITEMS = {
    "pop": "Pop",
    "rock": "Rock",
    "reggaeton": "Reggaetón",
    "jazz": "Jazz",
    "clásica": "Clásica",
    "indie": "Indie",
    "hip-hop": "Hip-Hop",
    "salsa": "Salsa",
    "electrónica": "Electrónica",
    "latin": "Latina",
    "folk": "Folk",
    "r&b": "R&B",
    "cumbia": "Cumbia",
    "metal": "Metal",
    "alternativa": "Alternativa",
    "k-pop": "K-Pop",
    "vallenato": "Vallenato",
    "bossa nova": "Bossa Nova",
    "soul": "Soul",
    "blues": "Blues",
    "trap": "Trap",
    "ambient": "Ambient",
    "house": "House",
    "techno": "Techno",
    "opera": "Ópera",
    "edm": "EDM",
}

PERSONALITY_SETS = {
    "intellectual": "Intelectual",
    "social": "Social",
    "leadership": "Liderazgo",
    "creative": "Creativo",
    "organized": "Organizado",
    "resilient": "Resiliente",
}

GOAL_SETS = {
    "academic_and_mentorship": "Académico y Mentoría",
    "sports_and_fitness": "Deportes y Bienestar",
    "social_and_campus_life": "Social y Vida Universitaria",
    "creative_and_competitive": "Creativo y Competitivo",
    "professional_and_entrepreneurial": "Profesional y Emprendimiento",
}

GOAL_SUBSETS = {
    "academic_study": "Estudio académico",
    "mentoring_relationship": "Mentoría",
    "recreational_sports": "Deportes recreativos",
    "fitness_training": "Entrenamiento físico",
    "campus_connections": "Conexiones en campus",
    "practical_social": "Social práctico",
    "community_service": "Servicio comunitario",
    "creative_projects": "Proyectos creativos",
    "competitive_activities": "Actividades competitivas",
    "entrepreneurship": "Emprendimiento",
    "career_networking": "Red profesional",
}

GOAL_ITEMS = {
    "study partner": "Compañero de estudio",
    "thesis partner": "Compañero de tesis",
    "research collaborator": "Colaborador de investigación",
    "seeking academic mentor": "Busco mentor académico",
    "open to mentoring": "Disponible para mentoría",
    "sports activity partner": "Compañero deportivo",
    "workout partner": "Compañero de entrenamiento",
    "campus friends": "Amigos en el campus",
    "open connections": "Conexiones abiertas",
    "housing & commute partner": "Compañero de vivienda/transporte",
    "language practice partner": "Compañero de idiomas",
    "volunteer partner": "Compañero de voluntariado",
    "creative collaborator": "Colaborador creativo",
    "gaming & esports partner": "Compañero de gaming/esports",
    "competition team": "Equipo de competencias",
    "startup co-founder": "Cofundador de startup",
    "professional networking": "Networking profesional",
    "default": "General",
}

ACADEMIC_AREAS = {
    "ARC": "Arquitectura",
    "BUS": "Negocios y Gestión",
    "COM": "Comunicación",
    "DSN": "Diseño",
    "EDU": "Educación",
    "ENG": "Ingeniería",
    "FIN": "Finanzas",
    "GLB": "Estudios Globales",
    "HLT": "Salud",
    "HUM": "Humanidades",
    "LAW": "Derecho",
    "SPT": "Deportes",
    "TEC": "Tecnología",
}

ACADEMIC_ITEMS = {
    "PARP": "Doctorado en Investigación Aplicada para Proyectos",
    "MADF": "Maestría en Arquitectura y Fabricación Digital",
    "MAID": "Maestría en Arquitectura y Diseño de Interiores",
    "MSARC": "Maestría en Arquitectura Sustentable",
    "BADM": "Licenciatura en Administración de Empresas",
    "BIBS": "Licenciatura en Negocios Internacionales",
    "BSMK": "Licenciatura en Marketing Estratégico",
    "PIRSS": "Doctorado en Innovación en Responsabilidad Social y Sustentabilidad",
    "PITOUR": "Doctorado Internacional en Turismo",
    "MBA": "Maestría en Administración de Empresas (MBA)",
    "MEBUS": "Maestría en Economía y Negocios",
    "MGBM": "Maestría en Gestión de Negocios Gastronómicos",
    "MHCD": "Maestría en Desarrollo de Capital Humano",
    "MSR": "Maestría en Responsabilidad Social",
    "MSHCM": "Maestría en Gestión Estratégica de Capital Humano",
    "MTDM": "Maestría en Gestión de Destinos Turísticos",
    "BCOM": "Licenciatura en Comunicación",
    "PCOMR": "Doctorado en Investigación en Comunicación",
    "PSCM": "Doctorado en Comunicación Estratégica y Marketing",
    "MCOMK": "Maestría en Comunicación y Marketing",
    "MEIM": "Maestría en Gestión de la Industria del Entretenimiento",
    "MICST": "Maestría en Comunicación Integral y Transformación Social",
    "MSJNM": "Maestría en Periodismo Estratégico y Nuevos Medios",
    "MSMM": "Maestría en Gestión Estratégica de Medios",
    "BFDI": "Licenciatura en Diseño de Moda e Innovación",
    "BGD": "Licenciatura en Diseño Gráfico",
    "BID": "Licenciatura en Diseño Industrial",
    "BMMD": "Licenciatura en Diseño Multimedia",
    "MAPD": "Maestría en Diseño Avanzado de Producto",
    "MFMK": "Maestría en Moda y Marketing",
    "PEE": "Doctorado en Evaluación Educativa",
    "PELIM": "Doctorado en Liderazgo Educativo y Gestión Institucional",
    "PIDS": "Doctorado en Estudios Interdisciplinarios",
    "MEDU": "Maestría en Educación",
    "MPPED": "Maestría en Psicopedagogía",
    "BCE": "Licenciatura en Ingeniería Civil",
    "BIEM": "Licenciatura en Ingeniería Industrial para la Gestión",
    "BMEC": "Licenciatura en Ingeniería Mecatrónica",
    "PIE": "Doctorado en Ingeniería Industrial",
    "MENGM": "Maestría en Gestión de Ingeniería",
    "MLOG": "Maestría en Logística",
    "MTSD": "Maestría en Tecnologías para el Desarrollo Sustentable",
    "BFPA": "Licenciatura en Finanzas y Contaduría Pública",
    "PACT": "Doctorado en Ciencias Actuariales",
    "MBFM": "Maestría en Banca y Mercados Financieros",
    "MFIN": "Maestría en Finanzas",
    "MRISK": "Maestría en Gestión de Riesgos",
    "PISEC": "Doctorado en Seguridad Internacional",
    "MIA": "Maestría en Asuntos Internacionales",
    "BMED": "Licenciatura en Medicina",
    "BPSY": "Licenciatura en Psicología",
    "PABIO": "Doctorado en Bioética Aplicada",
    "PHSC": "Doctorado en Ciencias de la Salud",
    "PNSC": "Doctorado en Ciencias de la Nutrición",
    "MBIO": "Maestría en Bioética",
    "MCN": "Maestría en Nutrición Clínica",
    "MCPSY": "Maestría en Psicología Clínica",
    "MGBIO": "Maestría en Bioética Global",
    "MHIM": "Maestría en Gestión de Instituciones de Salud",
    "MMED": "Maestría en Ciencias Médicas",
    "PHUM": "Doctorado en Humanidades",
    "PPHIL": "Doctorado en Filosofía",
    "MACUL": "Maestría en Culturas Antiguas",
    "MEQD": "Maestría en Equidad y Desarrollo",
    "MHUM": "Maestría en Humanidades",
    "MPPHI": "Maestría en Filosofía Personalista",
    "MPHIL": "Maestría en Filosofía",
    "MTPA": "Maestría en Teología y Acción Pastoral",
    "BLAW": "Licenciatura en Derecho",
    "PLAW": "Doctorado en Derecho",
    "PPA": "Doctorado en Administración Pública",
    "MCORLA": "Maestría en Derecho Corporativo",
    "MCRIM": "Maestría en Ciencias Penales",
    "MPA": "Maestría en Administración Pública",
    "MTAX": "Maestría en Derecho Fiscal y Administración Tributaria",
    "MSAS": "Maestría en Administración del Deporte y Ciencias Aplicadas",
    "BITDB": "Ingeniería en Tecnologías de la Información y Negocios Digitales",
    "MITAI": "Maestría en Tecnologías de la Información e Inteligencia Analítica",
    "MSTAT": "Maestría en Estadística",
}

RESEARCH_SETS = {
    "engineering_research": "Investigación en Ingeniería",
    "computer_science_research": "Investigación en Ciencias Computacionales",
    "data_science_research": "Investigación en Ciencia de Datos",
    "biomedical_research": "Investigación Biomédica",
    "business_and_economic_research": "Investigación en Negocios y Economía",
    "legal_research": "Investigación Jurídica",
    "communication_research": "Investigación en Comunicación",
    "design_research": "Investigación en Diseño",
    "architecture_research": "Investigación en Arquitectura",
    "educational_research": "Investigación Educativa",
    "humanities_research": "Investigación en Humanidades",
    "social_sciences_research": "Investigación en Ciencias Sociales",
    "health_and_sports_research": "Investigación en Salud y Deportes",
}

RESEARCH_ITEMS = {
    "renewable energy systems": "Sistemas de Energía Renovable",
    "smart materials": "Materiales Inteligentes",
    "autonomous vehicles": "Vehículos Autónomos",
    "smart manufacturing": "Manufactura Inteligente",
    "structural resilience": "Resiliencia Estructural",
    "green construction": "Construcción Verde",
    "industrial process optimization": "Optimización de Procesos Industriales",
    "mechatronic systems": "Sistemas Mecatrónicos",
    "energy efficiency": "Eficiencia Energética",
    "sustainable logistics": "Logística Sustentable",
    "machine learning theory": "Teoría de Machine Learning",
    "deep learning research": "Investigación en Deep Learning",
    "computer vision": "Visión por Computadora",
    "natural language processing research": "Investigación en Procesamiento de Lenguaje Natural",
    "reinforcement learning": "Aprendizaje por Refuerzo",
    "distributed systems": "Sistemas Distribuidos",
    "cybersecurity & privacy": "Ciberseguridad y Privacidad",
    "cryptography": "Criptografía",
    "programming languages theory": "Teoría de Lenguajes de Programación",
    "quantum computing": "Cómputo Cuántico",
    "software engineering practices": "Prácticas de Ingeniería de Software",
    "user experience research": "Investigación en Experiencia de Usuario",
    "causal inference": "Inferencia Causal",
    "bayesian statistics": "Estadística Bayesiana",
    "time series analysis": "Análisis de Series de Tiempo",
    "network science": "Ciencia de Redes",
    "big data systems": "Sistemas de Big Data",
    "data ethics": "Ética de Datos",
    "cancer research": "Investigación del Cáncer",
    "cardiovascular health": "Salud Cardiovascular",
    "neuroscience": "Neurociencia",
    "pharmacology research": "Investigación en Farmacología",
    "public health policy": "Política de Salud Pública",
    "clinical nutrition research": "Investigación en Nutrición Clínica",
    "epidemiological studies": "Estudios Epidemiológicos",
    "bioethics": "Bioética",
    "consumer behavior": "Comportamiento del Consumidor",
    "sustainable business strategy": "Estrategia de Negocios Sustentable",
    "esg & corporate responsibility": "ESG y Responsabilidad Corporativa",
    "corporate governance": "Gobierno Corporativo",
    "financial markets": "Mercados Financieros",
    "macroeconomics": "Macroeconomía",
    "microeconomics": "Microeconomía",
    "innovation studies": "Estudios de Innovación",
    "entrepreneurship research": "Investigación en Emprendimiento",
    "constitutional law research": "Investigación en Derecho Constitucional",
    "international law studies": "Estudios de Derecho Internacional",
    "tax law research": "Investigación en Derecho Fiscal",
    "public policy analysis": "Análisis de Políticas Públicas",
    "environmental law": "Derecho Ambiental",
    "criminal justice": "Justicia Penal",
    "human rights": "Derechos Humanos",
    "media effects": "Efectos de los Medios",
    "political communication": "Comunicación Política",
    "digital media studies": "Estudios de Medios Digitales",
    "public relations research": "Investigación en Relaciones Públicas",
    "advertising research": "Investigación en Publicidad",
    "service design": "Diseño de Servicios",
    "design thinking": "Design Thinking",
    "speculative design": "Diseño Especulativo",
    "bioclimatic architecture": "Arquitectura Bioclimática",
    "heritage conservation research": "Investigación en Conservación del Patrimonio",
    "smart cities": "Ciudades Inteligentes",
    "affordable housing": "Vivienda Asequible",
    "educational technology research": "Investigación en Tecnología Educativa",
    "curriculum development": "Desarrollo Curricular",
    "educational equity": "Equidad Educativa",
    "special education research": "Investigación en Educación Especial",
    "ancient philosophy": "Filosofía Antigua",
    "modern philosophy": "Filosofía Moderna",
    "ethics & moral philosophy": "Ética y Filosofía Moral",
    "religious studies": "Estudios Religiosos",
    "literary theory": "Teoría Literaria",
    "translation studies": "Estudios de Traducción",
    "classical studies": "Estudios Clásicos",
    "cultural heritage": "Patrimonio Cultural",
    "cognitive psychology": "Psicología Cognitiva",
    "clinical psychology research": "Investigación en Psicología Clínica",
    "social psychology": "Psicología Social",
    "geopolitics": "Geopolítica",
    "migration studies": "Estudios Migratorios",
    "gender studies": "Estudios de Género",
    "sports performance": "Rendimiento Deportivo",
    "sports psychology": "Psicología del Deporte",
    "default": "General",
    "3d printing": "Impresión 3D",
    "advertising": "Publicidad",
    "advocacy": "Incidencia Social",
    "ai": "Inteligencia Artificial",
    "ai governance": "Gobernanza de IA",
    "algorithmic trading": "Trading Algorítmico",
    "algorithms": "Algoritmos",
    "analytics": "Analítica",
    "anatomy": "Anatomía",
    "arduino": "Arduino",
    "argumentation": "Argumentación",
    "art history": "Historia del Arte",
    "automation": "Automatización",
    "backend development": "Desarrollo Backend",
    "behavior": "Comportamiento",
    "big data": "Big Data",
    "biochemistry": "Bioquímica",
    "biology": "Biología",
    "biomechanics": "Biomecánica",
    "branding": "Branding",
    "broadcasting": "Radiodifusión",
    "budgeting": "Presupuesto",
    "cardiology": "Cardiología",
    "ceramics": "Cerámica",
    "chess": "Ajedrez",
    "civic education": "Educación Cívica",
    "clinical psychology": "Psicología Clínica",
    "cloud": "Nube / Cloud",
    "coffee": "Café",
    "communication": "Comunicación",
    "communications": "Comunicaciones",
    "community": "Comunidad",
    "competitive programming": "Programación Competitiva",
    "compliance": "Cumplimiento Regulatorio",
    "constitutional law": "Derecho Constitucional",
    "construction": "Construcción",
    "construction management": "Gestión de Construcción",
    "content ai": "IA para Contenido",
    "content creation": "Creación de Contenido",
    "cooking": "Cocina",
    "corporate": "Corporativo",
    "corporate finance": "Finanzas Corporativas",
    "creative industries": "Industrias Creativas",
    "criminal law": "Derecho Penal",
    "critical thinking": "Pensamiento Crítico",
    "cs2": "CS2",
    "cultural diplomacy": "Diplomacia Cultural",
    "cultural economy": "Economía Cultural",
    "curriculum": "Currículo",
    "cycling": "Ciclismo",
    "dance": "Danza",
    "data": "Datos",
    "data privacy": "Privacidad de Datos",
    "deep learning": "Deep Learning",
    "dermatology": "Dermatología",
    "design": "Diseño",
    "design criticism": "Crítica del Diseño",
    "development": "Desarrollo",
    "devops": "DevOps",
    "dietetics": "Dietética",
    "digital fabrication": "Fabricación Digital",
    "digital marketing": "Marketing Digital",
    "digital transformation": "Transformación Digital",
    "diplomacy": "Diplomacia",
    "e-learning": "E-learning",
    "economic history": "Historia Económica",
    "economics": "Economía",
    "education policy": "Política Educativa",
    "efficiency": "Eficiencia",
    "emergency medicine": "Medicina de Urgencias",
    "energy": "Energía",
    "english": "Inglés",
    "entrepreneurship": "Emprendimiento",
    "epidemiology": "Epidemiología",
    "essays": "Ensayos",
    "ethics": "Ética",
    "ethics in education": "Ética en Educación",
    "events": "Eventos",
    "excel": "Excel",
    "fabrication": "Fabricación",
    "fashion": "Moda",
    "film": "Cine",
    "financial journalism": "Periodismo Financiero",
    "financial law": "Derecho Financiero",
    "financial literacy": "Educación Financiera",
    "fintech": "Fintech",
    "football": "Fútbol",
    "french": "Francés",
    "furniture design": "Diseño de Muebles",
    "gaming": "Gaming",
    "generative design": "Diseño Generativo",
    "genomics": "Genómica",
    "green building": "Edificación Sustentable",
    "growth": "Crecimiento",
    "growth hacking": "Growth Hacking",
    "gym": "Gimnasio",
    "gynecology": "Ginecología",
    "hardware": "Hardware",
    "health data": "Datos de Salud",
    "healthcare administration": "Administración de la Salud",
    "hiking": "Senderismo",
    "history": "Historia",
    "hospital management": "Gestión Hospitalaria",
    "human rights law": "Derecho de los Derechos Humanos",
    "human-computer interaction": "Interacción Humano-Computadora",
    "illustration": "Ilustración",
    "inclusive design": "Diseño Inclusivo",
    "infrastructure": "Infraestructura",
    "innovation": "Innovación",
    "interior design": "Diseño de Interiores",
    "internal medicine": "Medicina Interna",
    "international business": "Negocios Internacionales",
    "international development": "Desarrollo Internacional",
    "international finance": "Finanzas Internacionales",
    "international law": "Derecho Internacional",
    "international relations": "Relaciones Internacionales",
    "investment": "Inversión",
    "investments": "Inversiones",
    "ip law": "Propiedad Intelectual",
    "journaling": "Diario Personal",
    "journalism": "Periodismo",
    "jurisprudence": "Jurisprudencia",
    "justice": "Justicia",
    "law": "Derecho",
    "learning": "Aprendizaje",
    "legal philosophy": "Filosofía Jurídica",
    "legal tech": "Legal Tech",
    "literature": "Literatura",
    "logistics": "Logística",
    "machine learning": "Machine Learning",
    "management": "Gestión",
    "marketing": "Marketing",
    "materials": "Materiales",
    "media": "Medios",
    "media law": "Derecho de Medios",
    "media studies": "Estudios de Medios",
    "medical research": "Investigación Médica",
    "meditation": "Meditación",
    "modeling": "Modelado",
    "models": "Modelos",
    "moot court": "Tribunal Simulado",
    "multimedia": "Multimedia",
    "music": "Música",
    "negotiations": "Negociaciones",
    "networking": "Redes",
    "neurology": "Neurología",
    "ngos": "ONGs",
    "nlp": "PLN",
    "nutrition": "Nutrición",
    "opera": "Ópera",
    "operations": "Operaciones",
    "optimization": "Optimización",
    "parametric design": "Diseño Paramétrico",
    "pediatrics": "Pediatría",
    "performance metrics": "Métricas de Desempeño",
    "pharmacology": "Farmacología",
    "philosophy": "Filosofía",
    "photography": "Fotografía",
    "physiology": "Fisiología",
    "physiotherapy": "Fisioterapia",
    "pilates": "Pilates",
    "podcasting": "Podcasting",
    "poetry": "Poesía",
    "policy": "Política Pública",
    "political economy": "Economía Política",
    "political theory": "Teoría Política",
    "politics": "Política",
    "powerbuilding": "Powerbuilding",
    "probability": "Probabilidad",
    "product management": "Gestión de Producto",
    "prototyping": "Prototipado",
    "public affairs": "Asuntos Públicos",
    "public finance": "Finanzas Públicas",
    "public health": "Salud Pública",
    "public relations": "Relaciones Públicas",
    "public speaking": "Oratoria",
    "public spending": "Gasto Público",
    "quality management": "Gestión de Calidad",
    "quantitative finance": "Finanzas Cuantitativas",
    "reading": "Lectura",
    "regulation": "Regulación",
    "rehabilitation": "Rehabilitación",
    "research": "Investigación",
    "risk": "Riesgo",
    "risk management": "Gestión de Riesgo",
    "risk models": "Modelos de Riesgo",
    "running": "Correr",
    "saas": "SaaS",
    "sketching": "Bocetado",
    "skincare": "Cuidado de la Piel",
    "soccer": "Fútbol",
    "social media": "Redes Sociales",
    "social media ai": "IA en Redes Sociales",
    "spatial design": "Diseño Espacial",
    "special education": "Educación Especial",
    "sponsorship": "Patrocinio",
    "sports analytics": "Analítica Deportiva",
    "sports journalism": "Periodismo Deportivo",
    "sports marketing": "Marketing Deportivo",
    "sports medicine": "Medicina del Deporte",
    "sports nutrition": "Nutrición Deportiva",
    "startups": "Startups",
    "statistics": "Estadística",
    "stocks": "Bolsa de Valores",
    "strategy": "Estrategia",
    "strength training": "Entrenamiento de Fuerza",
    "structures": "Estructuras",
    "supply chain": "Cadena de Suministro",
    "surgery": "Cirugía",
    "sustainability": "Sustentabilidad",
    "sustainable urbanism": "Urbanismo Sustentable",
    "systems": "Sistemas",
    "systems architecture": "Arquitectura de Sistemas",
    "teaching": "Docencia",
    "tech policy": "Política Tecnológica",
    "therapy": "Terapia",
    "trade": "Comercio",
    "trading": "Trading",
    "transport": "Transporte",
    "travel": "Viajes",
    "treaties": "Tratados",
    "trends": "Tendencias",
    "ui/ux": "UI/UX",
    "urbanization": "Urbanización",
    "volleyball": "Voleibol",
    "wellness": "Bienestar",
    "wireframing": "Wireframing",
    "writing": "Escritura",
    "yoga": "Yoga",
}

# ---------------------------------------------------------------------------
# Catalog configuration: maps catalog filename to translation dicts
# ---------------------------------------------------------------------------

# Each entry: (sets_dict, subsets_dict_or_None, items_dict)
# subsets_dict is None when there are no subset labels to translate separately
# (subsets are translated using the same dict as sets for some catalogs,
# or have their own dict)

CATALOG_CONFIG = {
    "skill.json": {
        "type": "standard",
        "sets_dict": SKILL_SETS,
        "subsets_dict": None,  # skill subsets have no mapping provided; keep as-is
        "items_dict": SKILL_ITEMS,
    },
    "hobby.json": {
        "type": "standard",
        "sets_dict": HOBBY_SETS,
        "subsets_dict": None,
        "items_dict": HOBBY_ITEMS,
    },
    "sport.json": {
        "type": "standard",
        "sets_dict": SPORT_SETS,
        "subsets_dict": None,
        "items_dict": SPORT_ITEMS,
    },
    "music_genre.json": {
        "type": "standard",
        "sets_dict": MUSIC_SETS,
        "subsets_dict": None,
        "items_dict": MUSIC_ITEMS,
    },
    "personality_trait.json": {
        "type": "standard",
        "sets_dict": PERSONALITY_SETS,
        "subsets_dict": None,
        "items_dict": None,  # items already in Spanish
    },
    "goal.json": {
        "type": "standard",
        "sets_dict": GOAL_SETS,
        "subsets_dict": GOAL_SUBSETS,
        "items_dict": GOAL_ITEMS,
    },
    "academic.json": {
        "type": "academic",
        "areas_dict": ACADEMIC_AREAS,
        "items_dict": ACADEMIC_ITEMS,
    },
    "research_interest.json": {
        "type": "standard",
        "sets_dict": RESEARCH_SETS,
        "subsets_dict": None,
        "items_dict": RESEARCH_ITEMS,
    },
}

# campus.json intentionally omitted — no translations needed (already in Spanish)

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------


def translate_label(item_id, label, translation_dict):
    """Return the Spanish label for item_id if present, otherwise keep label."""
    if translation_dict is None:
        return label
    return translation_dict.get(item_id, label)


def translate_standard_catalog(data, sets_dict, subsets_dict, items_dict):
    """Translate sets, their subsets, and items in a standard catalog."""
    for s in data.get("sets", []):
        s["label"] = translate_label(s["id"], s["label"], sets_dict)
        for sub in s.get("subsets", []):
            if subsets_dict is not None:
                sub["label"] = translate_label(sub["id"], sub["label"], subsets_dict)

    for item in data.get("items", []):
        item["label"] = translate_label(item["id"], item["label"], items_dict)


def translate_academic_catalog(data, areas_dict, items_dict):
    """Translate areas and items in the academic catalog."""
    for area in data.get("areas", []):
        area["label"] = translate_label(area["id"], area["label"], areas_dict)

    for item in data.get("items", []):
        item["label"] = translate_label(item["id"], item["label"], items_dict)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    updated = []

    for filename, config in CATALOG_CONFIG.items():
        filepath = os.path.join(CATALOGS_DIR, filename)

        if not os.path.isfile(filepath):
            print(f"  SKIP  {filename} (file not found)")
            continue

        with open(filepath, "r", encoding="utf-8") as f:
            data = json.load(f)

        if config["type"] == "academic":
            translate_academic_catalog(
                data,
                areas_dict=config["areas_dict"],
                items_dict=config["items_dict"],
            )
        else:
            translate_standard_catalog(
                data,
                sets_dict=config["sets_dict"],
                subsets_dict=config["subsets_dict"],
                items_dict=config["items_dict"],
            )

        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write("\n")

        print(f"  OK    {filename}")
        updated.append(filename)

    print(f"\nDone. Updated {len(updated)} file(s).")


if __name__ == "__main__":
    main()
